#!/bin/sh

# The directory people will download the releases from.
# This will appear in the remote feed file.
#ARCHIVE_DIR_PUBLIC_URL='http://placeholder.org/releases/$RELEASE_VERSION'
ARCHIVE_DIR_PUBLIC_URL='http://ryppl.github.com/releases/0runner/$RELEASE_VERSION'

# The path to the main feed.
# The new version is added here when you publish a release.
#MASTER_FEED_FILE="$HOME/public_html/feeds/MyProg.xml"
MASTER_FEED_FILE="0runner.xml"

# A shell command to upload the generated archive file to the
# public server (corresponds to $ARCHIVE_DIR_PUBLIC_URL, which is
# used to download it again).
# If unset, you'll have to upload it yourself.
#ARCHIVE_UPLOAD_COMMAND='scp "$@" me@myhost:/var/www/releases/$RELEASE_VERSION/'
ARCHIVE_UPLOAD_COMMAND='echo adding "$@" && git add -A "$@" && git commit -m "0runner v1.0" && git push -u origin gh-pages'

# A shell command to upload the master feed ($MASTER_FEED_FILE) and
# related files to your web server. It will be downloaded using the
# feed's URL. If unset, you'll have to upload it yourself.
#MASTER_FEED_UPLOAD_COMMAND='scp "$@" me@myhost:/var/www/feeds/'
MASTER_FEED_UPLOAD_COMMAND='cp "$@" ~/src/ryppl/feeds/ && cd ~/src/ryppl/feeds && git add -A "$@" && git commit && git push -u origin gh-pages'

# Your public version control repository. When publishing, the new
# HEAD and the release tag will be pushed to this using a command
# such as "git-push main master v0.1"
# If unset, you'll have to update it yourself.
#PUBLIC_SCM_REPOSITORY=origin
PUBLIC_SCM_REPOSITORY=origin

cd `dirname "$0"`
exec 0launch http://0install.net/2007/interfaces/0release.xml --release /Users/dave/src/ryppl/0runner/0runner.xml \
 --archive-dir-public-url="$ARCHIVE_DIR_PUBLIC_URL" \
 --master-feed-file="$MASTER_FEED_FILE" \
 --archive-upload-command="$ARCHIVE_UPLOAD_COMMAND" \
 --master-feed-upload-command="$MASTER_FEED_UPLOAD_COMMAND" \
 --public-scm-repository="$PUBLIC_SCM_REPOSITORY" \
 -k 4E7A5231 \
 "$@"
